# Generated by Django 3.0.8 on 2020-07-01 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=10)),
                ('pub_date', models.DateTimeField(auto_now_add=True)),
                ('file_dir', models.CharField(max_length=100)),
                ('content', models.TextField()),
            ],
        ),
    ]
